### ISSUE TITLE
Typo in "pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git"

### ISSUE THREAD

**Issue by andremakes** [ISEDemoLab/Upgrade_ISE_in_Hybrid_Cloud#1]
Here:
pip install — upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git
ERROR: Invalid requirement: '—'

Should be:
pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git

Thanks!

**Comment by ISEDemoLab** [comment]
Thank you, fixed.

**Comment by ISEDemoLab** [comment]
Fixed typo
